export type JobLocationKind = "city" | "country" | "region";

export type JobLocation = {
  id: string;
  label: string;
  kind: JobLocationKind;
  countryId: string;
  aliases: string[];
  indeed: string;
  jobicyGeo?: string;
};

function country(
  id: string,
  label: string,
  aliases: string[],
  indeed: string,
  jobicyGeo?: string,
): JobLocation {
  return {
    id,
    label,
    kind: "country",
    countryId: id,
    aliases,
    indeed,
    jobicyGeo,
  };
}

function city(
  id: string,
  label: string,
  countryId: string,
  aliases: string[],
  indeed: string,
): JobLocation {
  return { id, label, kind: "city", countryId, aliases, indeed };
}

/** Every ISO country (French label) so the picker is not France-only. */
export const CATALOG_COUNTRIES: JobLocation[] = [
  country("france", "France", ["fr", "french", "hexagone"], "France", "france"),
  country("maroc", "Maroc", ["morocco", "ma", "moroccan"], "Morocco", "morocco"),
  country("algerie", "Algérie", ["algeria", "dz", "algerie"], "Algeria", "algeria"),
  country("tunisie", "Tunisie", ["tunisia", "tn"], "Tunisia", "tunisia"),
  country("senegal", "Sénégal", ["senegal", "sn"], "Senegal", "senegal"),
  country("cote-divoire", "Côte d’Ivoire", ["ivory coast", "ci", "côte d'ivoire", "cote d ivoire"], "Ivory Coast"),
  country("cameroun", "Cameroun", ["cameroon", "cm"], "Cameroon"),
  country("rdc", "RD Congo", ["congo", "drc", "kinshasa", "zaire"], "Democratic Republic of the Congo"),
  country("egypte", "Égypte", ["egypt", "eg"], "Egypt", "egypt"),
  country("afrique-du-sud", "Afrique du Sud", ["south africa", "za"], "South Africa", "south africa"),
  country("nigeria", "Nigeria", ["ng"], "Nigeria", "nigeria"),
  country("kenya", "Kenya", ["ke"], "Kenya", "kenya"),
  country("ghana", "Ghana", ["gh"], "Ghana"),
  country("benin", "Bénin", ["benin", "bj"], "Benin"),
  country("togo", "Togo", ["tg"], "Togo"),
  country("mali", "Mali", ["ml"], "Mali"),
  country("burkina", "Burkina Faso", ["bf"], "Burkina Faso"),
  country("guinee", "Guinée", ["guinea", "gn"], "Guinea"),
  country("madagascar", "Madagascar", ["mg"], "Madagascar"),
  country("maurice", "Maurice", ["mauritius", "mu"], "Mauritius"),
  country("rwanda", "Rwanda", ["rw"], "Rwanda"),
  country("belgique", "Belgique", ["belgium", "be", "belgian"], "Belgium", "belgium"),
  country("suisse", "Suisse", ["switzerland", "swiss", "ch"], "Switzerland", "switzerland"),
  country("luxembourg", "Luxembourg", ["lu"], "Luxembourg", "luxembourg"),
  country("allemagne", "Allemagne", ["germany", "de", "deutschland"], "Germany", "germany"),
  country("pays-bas", "Pays-Bas", ["netherlands", "holland", "nl"], "Netherlands", "netherlands"),
  country("espagne", "Espagne", ["spain", "es", "espana", "españa"], "Spain", "spain"),
  country("portugal", "Portugal", ["pt"], "Portugal", "portugal"),
  country("italie", "Italie", ["italy", "it"], "Italy", "italy"),
  country("royaume-uni", "Royaume-Uni", ["uk", "united kingdom", "britain", "england"], "United Kingdom", "uk"),
  country("irlande", "Irlande", ["ireland", "ie"], "Ireland", "ireland"),
  country("suede", "Suède", ["sweden", "se"], "Sweden", "sweden"),
  country("norvege", "Norvège", ["norway", "no"], "Norway", "norway"),
  country("danemark", "Danemark", ["denmark", "dk"], "Denmark", "denmark"),
  country("finlande", "Finlande", ["finland", "fi"], "Finland", "finland"),
  country("pologne", "Pologne", ["poland", "pl"], "Poland", "poland"),
  country("roumanie", "Roumanie", ["romania", "ro"], "Romania", "romania"),
  country("republique-tcheque", "République tchèque", ["czech", "czechia", "cz"], "Czech Republic"),
  country("autriche", "Autriche", ["austria", "at"], "Austria", "austria"),
  country("grece", "Grèce", ["greece", "gr"], "Greece"),
  country("hongrie", "Hongrie", ["hungary", "hu"], "Hungary"),
  country("bulgarie", "Bulgarie", ["bulgaria", "bg"], "Bulgaria"),
  country("croatie", "Croatie", ["croatia", "hr"], "Croatia"),
  country("serbie", "Serbie", ["serbia", "rs"], "Serbia"),
  country("ukraine", "Ukraine", ["ua"], "Ukraine"),
  country("russie", "Russie", ["russia", "ru"], "Russia"),
  country("turquie", "Turquie", ["turkey", "tr", "turkiye"], "Turkey", "turkey"),
  country("canada", "Canada", ["ca", "quebec", "québec"], "Canada", "canada"),
  country("etats-unis", "États-Unis", ["usa", "us", "united states", "america"], "United States", "usa"),
  country("mexique", "Mexique", ["mexico", "mx"], "Mexico", "mexico"),
  country("bresil", "Brésil", ["brazil", "br"], "Brazil", "brazil"),
  country("argentine", "Argentine", ["argentina", "ar"], "Argentina"),
  country("chili", "Chili", ["chile", "cl"], "Chile"),
  country("colombie", "Colombie", ["colombia", "co"], "Colombia"),
  country("emirats", "Émirats arabes unis", ["uae", "dubai", "abu dhabi"], "United Arab Emirates", "united arab emirates"),
  country("arabie-saoudite", "Arabie saoudite", ["saudi", "sa", "ksa"], "Saudi Arabia"),
  country("qatar", "Qatar", ["qa"], "Qatar"),
  country("israel", "Israël", ["israel", "il"], "Israel", "israel"),
  country("liban", "Liban", ["lebanon", "lb"], "Lebanon"),
  country("jordanie", "Jordanie", ["jordan", "jo"], "Jordan"),
  country("inde", "Inde", ["india", "in"], "India", "india"),
  country("pakistan", "Pakistan", ["pk"], "Pakistan"),
  country("bangladesh", "Bangladesh", ["bd"], "Bangladesh"),
  country("sri-lanka", "Sri Lanka", ["lk"], "Sri Lanka"),
  country("chine", "Chine", ["china", "cn"], "China", "china"),
  country("japon", "Japon", ["japan", "jp"], "Japan", "japan"),
  country("coree-du-sud", "Corée du Sud", ["south korea", "korea", "kr"], "South Korea", "south korea"),
  country("singapour", "Singapour", ["singapore", "sg"], "Singapore", "singapore"),
  country("malaisie", "Malaisie", ["malaysia", "my"], "Malaysia"),
  country("indonesie", "Indonésie", ["indonesia", "id"], "Indonesia"),
  country("thailande", "Thaïlande", ["thailand", "th"], "Thailand"),
  country("vietnam", "Viêt Nam", ["vietnam", "vn"], "Vietnam"),
  country("philippines", "Philippines", ["ph"], "Philippines"),
  country("australie", "Australie", ["australia", "au"], "Australia", "australia"),
  country("nouvelle-zelande", "Nouvelle-Zélande", ["new zealand", "nz"], "New Zealand"),
  country("europe", "Europe", ["eu", "ue", "emea", "european union"], "Europe"),
  country("afrique", "Afrique", ["africa"], "Africa"),
  country("monde", "Monde entier", ["worldwide", "remote worldwide", "global"], "Worldwide"),
];

export const CATALOG_CITIES: JobLocation[] = [
  city("casablanca", "Casablanca", "maroc", ["casa", "dar el beida"], "Casablanca"),
  city("rabat", "Rabat", "maroc", [], "Rabat"),
  city("marrakech", "Marrakech", "maroc", ["marrakesh"], "Marrakech"),
  city("tanger", "Tanger", "maroc", ["tangier"], "Tangier"),
  city("fes", "Fès", "maroc", ["fez", "fes"], "Fes"),
  city("agadir", "Agadir", "maroc", [], "Agadir"),
  city("meknes", "Meknès", "maroc", ["meknes"], "Meknes"),
  city("oujda", "Oujda", "maroc", [], "Oujda"),
  city("kenitra", "Kénitra", "maroc", ["kenitra"], "Kenitra"),
  city("tetouan", "Tétouan", "maroc", ["tetouan"], "Tetouan"),
  city("alger", "Alger", "algerie", ["algiers"], "Algiers"),
  city("oran", "Oran", "algerie", [], "Oran"),
  city("constantine", "Constantine", "algerie", [], "Constantine"),
  city("tunis", "Tunis", "tunisie", [], "Tunis"),
  city("sfax", "Sfax", "tunisie", [], "Sfax"),
  city("sousse", "Sousse", "tunisie", [], "Sousse"),
  city("dakar", "Dakar", "senegal", [], "Dakar"),
  city("abidjan", "Abidjan", "cote-divoire", [], "Abidjan"),
  city("douala", "Douala", "cameroun", [], "Douala"),
  city("yaounde", "Yaoundé", "cameroun", ["yaounde"], "Yaounde"),
  city("lagos", "Lagos", "nigeria", [], "Lagos"),
  city("nairobi", "Nairobi", "kenya", [], "Nairobi"),
  city("le-caire", "Le Caire", "egypte", ["cairo"], "Cairo"),
  city("johannesburg", "Johannesburg", "afrique-du-sud", ["joburg"], "Johannesburg"),
  city("cape-town", "Le Cap", "afrique-du-sud", ["cape town"], "Cape Town"),
  city("paris", "Paris", "france", ["idf", "ile de france", "île-de-france", "75"], "Paris"),
  city("lyon", "Lyon", "france", ["villeurbanne", "69", "rhone", "rhône"], "Lyon"),
  city("marseille", "Marseille", "france", ["13", "aix"], "Marseille"),
  city("toulouse", "Toulouse", "france", ["31"], "Toulouse"),
  city("lille", "Lille", "france", ["59", "roubaix", "nord"], "Lille"),
  city("nantes", "Nantes", "france", ["44"], "Nantes"),
  city("bordeaux", "Bordeaux", "france", ["33", "gironde"], "Bordeaux"),
  city("rennes", "Rennes", "france", ["35"], "Rennes"),
  city("grenoble", "Grenoble", "france", ["38"], "Grenoble"),
  city("montpellier", "Montpellier", "france", ["34"], "Montpellier"),
  city("strasbourg", "Strasbourg", "france", ["67"], "Strasbourg"),
  city("nice", "Nice", "france", ["06"], "Nice"),
  city("rouen", "Rouen", "france", ["76"], "Rouen"),
  city("tours", "Tours", "france", ["37"], "Tours"),
  city("dijon", "Dijon", "france", ["21"], "Dijon"),
  city("angers", "Angers", "france", ["49"], "Angers"),
  city("clermont-ferrand", "Clermont-Ferrand", "france", ["clermont"], "Clermont-Ferrand"),
  city("reims", "Reims", "france", ["51"], "Reims"),
  city("aix-en-provence", "Aix-en-Provence", "france", ["aix"], "Aix-en-Provence"),
  city("orleans", "Orléans", "france", ["orleans"], "Orléans"),
  city("metz", "Metz", "france", ["57"], "Metz"),
  city("nancy", "Nancy", "france", ["54"], "Nancy"),
  city("caen", "Caen", "france", ["14"], "Caen"),
  city("brest", "Brest", "france", ["29"], "Brest"),
  city("annecy", "Annecy", "france", ["74"], "Annecy"),
  city("toulon", "Toulon", "france", ["83"], "Toulon"),
  city("ile-de-france", "Île-de-France", "france", ["idf", "paris region"], "Île-de-France"),
  city("bruxelles", "Bruxelles", "belgique", ["brussels", "brussel"], "Brussels"),
  city("anvers", "Anvers", "belgique", ["antwerp"], "Antwerp"),
  city("liege", "Liège", "belgique", ["liege"], "Liège"),
  city("geneve", "Genève", "suisse", ["geneva"], "Geneva"),
  city("lausanne", "Lausanne", "suisse", [], "Lausanne"),
  city("zurich", "Zurich", "suisse", ["zürich"], "Zurich"),
  city("berlin", "Berlin", "allemagne", [], "Berlin"),
  city("munich", "Munich", "allemagne", ["munchen", "münchen"], "Munich"),
  city("hambourg", "Hambourg", "allemagne", ["hamburg"], "Hamburg"),
  city("amsterdam", "Amsterdam", "pays-bas", [], "Amsterdam"),
  city("rotterdam", "Rotterdam", "pays-bas", [], "Rotterdam"),
  city("madrid", "Madrid", "espagne", [], "Madrid"),
  city("barcelone", "Barcelone", "espagne", ["barcelona"], "Barcelona"),
  city("lisbonne", "Lisbonne", "portugal", ["lisbon"], "Lisbon"),
  city("porto", "Porto", "portugal", [], "Porto"),
  city("rome", "Rome", "italie", ["roma"], "Rome"),
  city("milan", "Milan", "italie", ["milano"], "Milan"),
  city("londres", "Londres", "royaume-uni", ["london"], "London"),
  city("manchester", "Manchester", "royaume-uni", [], "Manchester"),
  city("dublin", "Dublin", "irlande", [], "Dublin"),
  city("montreal", "Montréal", "canada", ["montreal"], "Montreal"),
  city("toronto", "Toronto", "canada", [], "Toronto"),
  city("vancouver", "Vancouver", "canada", [], "Vancouver"),
  city("new-york", "New York", "etats-unis", ["nyc", "new york city"], "New York"),
  city("san-francisco", "San Francisco", "etats-unis", ["sf", "bay area"], "San Francisco"),
  city("seattle", "Seattle", "etats-unis", [], "Seattle"),
  city("austin", "Austin", "etats-unis", [], "Austin"),
  city("boston", "Boston", "etats-unis", [], "Boston"),
  city("dubai", "Dubaï", "emirats", ["dubai"], "Dubai"),
  city("abu-dhabi", "Abou Dabi", "emirats", ["abu dhabi"], "Abu Dhabi"),
  city("tel-aviv", "Tel Aviv", "israel", ["tel aviv"], "Tel Aviv"),
  city("bangalore", "Bangalore", "inde", ["bengaluru"], "Bangalore"),
  city("hyderabad", "Hyderabad", "inde", [], "Hyderabad"),
  city("singapour-ville", "Singapour", "singapour", ["singapore"], "Singapore"),
  city("sydney", "Sydney", "australie", [], "Sydney"),
  city("melbourne", "Melbourne", "australie", [], "Melbourne"),
];

export const POPULAR_LOCATION_IDS = [
  "maroc",
  "casablanca",
  "france",
  "paris",
  "rabat",
  "lyon",
  "belgique",
  "canada",
  "emirats",
  "europe",
];
