import type { Audience, PricingModel, ToolCategory } from "@/modules/dev-tools/types";

/**
 * The tools we always want in the catalogue, whatever GitHub discovery brings
 * back that day. Repositories are measured; hosted products without a public
 * repo get an editorial baseline that the scrape and the LLM then refine.
 */
export type ToolSeed = {
  slug: string;
  name: string;
  category: ToolCategory;
  websiteUrl: string;
  /** Where the vendor states its plans. Scraped for the free tier and entry price. */
  pricingUrl?: string;
  docsUrl?: string;
  /** `owner/name` — presence of this is what makes a row measurable. */
  repo?: string;
  pricingModel?: PricingModel;
  audience?: Audience;
  tagline?: string;
  /** Starting point for products we cannot measure. 0-100. */
  baselinePopularity?: number;
  baselineStability?: number;
};

export const TOOL_SEEDS: ToolSeed[] = [
  // ---------------------------------------------------------------- ai_api
  {
    slug: "openai",
    name: "OpenAI",
    category: "ai_api",
    websiteUrl: "https://openai.com",
    pricingUrl: "https://openai.com/api/pricing",
    pricingModel: "usage",
    tagline: "Modèles GPT par API, facturés au token.",
    baselinePopularity: 98,
    baselineStability: 85,
  },
  {
    slug: "anthropic",
    name: "Anthropic Claude",
    category: "ai_api",
    websiteUrl: "https://anthropic.com",
    pricingUrl: "https://www.anthropic.com/pricing",
    pricingModel: "usage",
    tagline: "Modèles Claude, forts en code et long contexte.",
    baselinePopularity: 90,
    baselineStability: 84,
  },
  {
    slug: "google-gemini",
    name: "Google Gemini API",
    category: "ai_api",
    websiteUrl: "https://ai.google.dev",
    pricingUrl: "https://ai.google.dev/pricing",
    pricingModel: "freemium",
    tagline: "Palier gratuit réel sur les modèles Flash.",
    baselinePopularity: 88,
    baselineStability: 82,
  },
  {
    slug: "mistral",
    name: "Mistral AI",
    category: "ai_api",
    websiteUrl: "https://mistral.ai",
    pricingUrl: "https://mistral.ai/pricing",
    pricingModel: "usage",
    tagline: "Modèles européens, hébergement UE.",
    baselinePopularity: 74,
    baselineStability: 74,
  },
  {
    slug: "groq",
    name: "Groq",
    category: "ai_api",
    websiteUrl: "https://groq.com",
    pricingUrl: "https://groq.com/pricing",
    pricingModel: "freemium",
    tagline: "Inférence très rapide sur modèles ouverts.",
    baselinePopularity: 76,
    baselineStability: 70,
  },
  {
    slug: "deepseek",
    name: "DeepSeek",
    category: "ai_api",
    websiteUrl: "https://platform.deepseek.com",
    pricingUrl: "https://api-docs.deepseek.com/quick_start/pricing",
    pricingModel: "usage",
    tagline: "Prix par token parmi les plus bas du marché.",
    baselinePopularity: 78,
    baselineStability: 65,
  },
  {
    slug: "openrouter",
    name: "OpenRouter",
    category: "ai_api",
    websiteUrl: "https://openrouter.ai",
    pricingUrl: "https://openrouter.ai/models",
    pricingModel: "usage",
    tagline: "Une seule API pour des centaines de modèles.",
    baselinePopularity: 75,
    baselineStability: 68,
  },
  {
    slug: "together-ai",
    name: "Together AI",
    category: "ai_api",
    websiteUrl: "https://together.ai",
    pricingUrl: "https://www.together.ai/pricing",
    pricingModel: "usage",
    baselinePopularity: 66,
    baselineStability: 66,
  },
  {
    slug: "ollama",
    name: "Ollama",
    category: "ai_api",
    websiteUrl: "https://ollama.com",
    repo: "ollama/ollama",
    pricingModel: "open_source",
    audience: "solo",
    tagline: "Modèles ouverts exécutés sur ta machine, sans coût d’API.",
  },
  {
    slug: "litellm",
    name: "LiteLLM",
    category: "ai_api",
    websiteUrl: "https://litellm.ai",
    repo: "BerriAI/litellm",
    pricingModel: "open_source",
    tagline: "Proxy unifié vers 100+ fournisseurs de LLM.",
  },
  {
    slug: "vllm",
    name: "vLLM",
    category: "ai_api",
    websiteUrl: "https://docs.vllm.ai",
    repo: "vllm-project/vllm",
    pricingModel: "open_source",
    audience: "pro",
    tagline: "Serveur d’inférence auto-hébergé haute performance.",
  },

  // --------------------------------------------------------------- hosting
  {
    slug: "vercel",
    name: "Vercel",
    category: "hosting",
    websiteUrl: "https://vercel.com",
    pricingUrl: "https://vercel.com/pricing",
    pricingModel: "freemium",
    tagline: "Déploiement Next.js sans configuration.",
    baselinePopularity: 92,
    baselineStability: 86,
  },
  {
    slug: "netlify",
    name: "Netlify",
    category: "hosting",
    websiteUrl: "https://netlify.com",
    pricingUrl: "https://www.netlify.com/pricing",
    pricingModel: "freemium",
    baselinePopularity: 82,
    baselineStability: 84,
  },
  {
    slug: "cloudflare",
    name: "Cloudflare Pages & Workers",
    category: "hosting",
    websiteUrl: "https://cloudflare.com",
    pricingUrl: "https://developers.cloudflare.com/workers/platform/pricing",
    pricingModel: "freemium",
    tagline: "Edge compute avec un palier gratuit très large.",
    baselinePopularity: 90,
    baselineStability: 90,
  },
  {
    slug: "railway",
    name: "Railway",
    category: "hosting",
    websiteUrl: "https://railway.app",
    pricingUrl: "https://railway.com/pricing",
    pricingModel: "usage",
    baselinePopularity: 74,
    baselineStability: 72,
  },
  {
    slug: "fly-io",
    name: "Fly.io",
    category: "hosting",
    websiteUrl: "https://fly.io",
    pricingUrl: "https://fly.io/docs/about/pricing",
    pricingModel: "usage",
    baselinePopularity: 72,
    baselineStability: 74,
  },
  {
    slug: "render",
    name: "Render",
    category: "hosting",
    websiteUrl: "https://render.com",
    pricingUrl: "https://render.com/pricing",
    pricingModel: "freemium",
    baselinePopularity: 70,
    baselineStability: 74,
  },
  {
    slug: "coolify",
    name: "Coolify",
    category: "hosting",
    websiteUrl: "https://coolify.io",
    repo: "coollabsio/coolify",
    pricingModel: "open_source",
    audience: "solo",
    tagline: "PaaS auto-hébergé : Vercel-like sur ton propre VPS.",
  },
  {
    slug: "dokploy",
    name: "Dokploy",
    category: "hosting",
    websiteUrl: "https://dokploy.com",
    repo: "Dokploy/dokploy",
    pricingModel: "open_source",
    audience: "solo",
  },
  {
    slug: "deno-deploy",
    name: "Deno Deploy",
    category: "hosting",
    websiteUrl: "https://deno.com/deploy",
    pricingUrl: "https://deno.com/deploy/pricing",
    pricingModel: "freemium",
    baselinePopularity: 62,
    baselineStability: 70,
  },

  // -------------------------------------------------------------- database
  {
    slug: "supabase",
    name: "Supabase",
    category: "database",
    websiteUrl: "https://supabase.com",
    pricingUrl: "https://supabase.com/pricing",
    repo: "supabase/supabase",
    pricingModel: "freemium",
    tagline: "Postgres managé avec auth, storage et realtime.",
  },
  {
    slug: "neon",
    name: "Neon",
    category: "database",
    websiteUrl: "https://neon.tech",
    pricingUrl: "https://neon.com/pricing",
    repo: "neondatabase/neon",
    pricingModel: "freemium",
    tagline: "Postgres serverless avec branches par PR.",
  },
  {
    slug: "turso",
    name: "Turso",
    category: "database",
    websiteUrl: "https://turso.tech",
    pricingUrl: "https://turso.tech/pricing",
    pricingModel: "freemium",
    tagline: "SQLite répliqué en edge.",
    baselinePopularity: 62,
    baselineStability: 62,
  },
  {
    slug: "planetscale",
    name: "PlanetScale",
    category: "database",
    websiteUrl: "https://planetscale.com",
    pricingUrl: "https://planetscale.com/pricing",
    pricingModel: "paid",
    audience: "pro",
    baselinePopularity: 70,
    baselineStability: 80,
  },
  {
    slug: "upstash",
    name: "Upstash",
    category: "database",
    websiteUrl: "https://upstash.com",
    pricingUrl: "https://upstash.com/pricing",
    pricingModel: "freemium",
    tagline: "Redis et Kafka serverless facturés à la requête.",
    baselinePopularity: 68,
    baselineStability: 70,
  },
  {
    slug: "mongodb-atlas",
    name: "MongoDB Atlas",
    category: "database",
    websiteUrl: "https://mongodb.com/atlas",
    pricingUrl: "https://www.mongodb.com/pricing",
    pricingModel: "freemium",
    baselinePopularity: 88,
    baselineStability: 88,
  },
  {
    slug: "pocketbase",
    name: "PocketBase",
    category: "database",
    websiteUrl: "https://pocketbase.io",
    repo: "pocketbase/pocketbase",
    pricingModel: "open_source",
    audience: "solo",
    tagline: "Backend complet en un seul binaire.",
  },
  {
    slug: "postgresql",
    name: "PostgreSQL",
    category: "database",
    websiteUrl: "https://www.postgresql.org",
    repo: "postgres/postgres",
    pricingModel: "open_source",
    tagline: "La base relationnelle de référence.",
  },
  {
    slug: "redis",
    name: "Redis",
    category: "database",
    websiteUrl: "https://redis.io",
    repo: "redis/redis",
    pricingModel: "open_source",
  },
  {
    slug: "surrealdb",
    name: "SurrealDB",
    category: "database",
    websiteUrl: "https://surrealdb.com",
    repo: "surrealdb/surrealdb",
    pricingModel: "open_source",
  },

  // ------------------------------------------------------------------ auth
  {
    slug: "clerk",
    name: "Clerk",
    category: "auth",
    websiteUrl: "https://clerk.com",
    pricingUrl: "https://clerk.com/pricing",
    pricingModel: "freemium",
    tagline: "Auth clé en main avec composants React.",
    baselinePopularity: 78,
    baselineStability: 76,
  },
  {
    slug: "auth0",
    name: "Auth0",
    category: "auth",
    websiteUrl: "https://auth0.com",
    pricingUrl: "https://auth0.com/pricing",
    pricingModel: "freemium",
    audience: "enterprise",
    baselinePopularity: 86,
    baselineStability: 88,
  },
  {
    slug: "better-auth",
    name: "Better Auth",
    category: "auth",
    websiteUrl: "https://better-auth.com",
    repo: "better-auth/better-auth",
    pricingModel: "open_source",
    tagline: "Auth TypeScript hébergée avec ton app, sans coût par utilisateur.",
  },
  {
    slug: "authjs",
    name: "Auth.js (NextAuth)",
    category: "auth",
    websiteUrl: "https://authjs.dev",
    repo: "nextauthjs/next-auth",
    pricingModel: "open_source",
  },
  {
    slug: "keycloak",
    name: "Keycloak",
    category: "auth",
    websiteUrl: "https://keycloak.org",
    repo: "keycloak/keycloak",
    pricingModel: "open_source",
    audience: "enterprise",
    tagline: "SSO et SAML complets, auto-hébergés.",
  },
  {
    slug: "logto",
    name: "Logto",
    category: "auth",
    websiteUrl: "https://logto.io",
    pricingUrl: "https://logto.io/pricing",
    repo: "logto-io/logto",
    pricingModel: "freemium",
  },
  {
    slug: "zitadel",
    name: "Zitadel",
    category: "auth",
    websiteUrl: "https://zitadel.com",
    pricingUrl: "https://zitadel.com/pricing",
    repo: "zitadel/zitadel",
    pricingModel: "freemium",
    audience: "pro",
  },
  {
    slug: "ory-kratos",
    name: "Ory Kratos",
    category: "auth",
    websiteUrl: "https://www.ory.sh",
    repo: "ory/kratos",
    pricingModel: "open_source",
    audience: "pro",
  },
  {
    slug: "workos",
    name: "WorkOS",
    category: "auth",
    websiteUrl: "https://workos.com",
    pricingUrl: "https://workos.com/pricing",
    pricingModel: "freemium",
    audience: "enterprise",
    baselinePopularity: 66,
    baselineStability: 76,
  },

  // ----------------------------------------------------------------- ci_cd
  {
    slug: "github",
    name: "GitHub & Actions",
    category: "ci_cd",
    websiteUrl: "https://github.com",
    pricingUrl: "https://github.com/pricing",
    pricingModel: "freemium",
    tagline: "Dépôts privés illimités et 2 000 minutes de CI par mois.",
    baselinePopularity: 99,
    baselineStability: 95,
  },
  {
    slug: "gitlab",
    name: "GitLab",
    category: "ci_cd",
    websiteUrl: "https://gitlab.com",
    pricingUrl: "https://about.gitlab.com/pricing",
    pricingModel: "freemium",
    baselinePopularity: 84,
    baselineStability: 88,
  },
  {
    slug: "circleci",
    name: "CircleCI",
    category: "ci_cd",
    websiteUrl: "https://circleci.com",
    pricingUrl: "https://circleci.com/pricing",
    pricingModel: "freemium",
    audience: "pro",
    baselinePopularity: 70,
    baselineStability: 82,
  },
  {
    slug: "woodpecker-ci",
    name: "Woodpecker CI",
    category: "ci_cd",
    websiteUrl: "https://woodpecker-ci.org",
    repo: "woodpecker-ci/woodpecker",
    pricingModel: "open_source",
    tagline: "CI auto-hébergée légère, pilotée par un fichier YAML.",
  },
  {
    slug: "argo-cd",
    name: "Argo CD",
    category: "ci_cd",
    websiteUrl: "https://argo-cd.readthedocs.io",
    repo: "argoproj/argo-cd",
    pricingModel: "open_source",
    audience: "enterprise",
  },
  {
    slug: "dagger",
    name: "Dagger",
    category: "ci_cd",
    websiteUrl: "https://dagger.io",
    repo: "dagger/dagger",
    pricingModel: "open_source",
    audience: "pro",
  },
  {
    slug: "jenkins",
    name: "Jenkins",
    category: "ci_cd",
    websiteUrl: "https://www.jenkins.io",
    repo: "jenkinsci/jenkins",
    pricingModel: "open_source",
    audience: "enterprise",
  },

  // ------------------------------------------------------------ monitoring
  {
    slug: "sentry",
    name: "Sentry",
    category: "monitoring",
    websiteUrl: "https://sentry.io",
    pricingUrl: "https://sentry.io/pricing",
    repo: "getsentry/sentry",
    pricingModel: "freemium",
    tagline: "Suivi des erreurs et des performances.",
  },
  {
    slug: "datadog",
    name: "Datadog",
    category: "monitoring",
    websiteUrl: "https://datadoghq.com",
    pricingUrl: "https://www.datadoghq.com/pricing",
    pricingModel: "paid",
    audience: "enterprise",
    baselinePopularity: 88,
    baselineStability: 90,
  },
  {
    slug: "grafana",
    name: "Grafana",
    category: "monitoring",
    websiteUrl: "https://grafana.com",
    pricingUrl: "https://grafana.com/pricing",
    repo: "grafana/grafana",
    pricingModel: "freemium",
  },
  {
    slug: "better-stack",
    name: "Better Stack",
    category: "monitoring",
    websiteUrl: "https://betterstack.com",
    pricingUrl: "https://betterstack.com/pricing",
    pricingModel: "freemium",
    baselinePopularity: 60,
    baselineStability: 68,
  },
  {
    slug: "uptime-kuma",
    name: "Uptime Kuma",
    category: "monitoring",
    websiteUrl: "https://uptime.kuma.pet",
    repo: "louislam/uptime-kuma",
    pricingModel: "open_source",
    audience: "solo",
    tagline: "Surveillance d’uptime auto-hébergée, installation en une commande.",
  },
  {
    slug: "signoz",
    name: "SigNoz",
    category: "monitoring",
    websiteUrl: "https://signoz.io",
    pricingUrl: "https://signoz.io/pricing",
    repo: "SigNoz/signoz",
    pricingModel: "open_source",
    tagline: "Alternative open source à Datadog, basée sur OpenTelemetry.",
  },
  {
    slug: "posthog",
    name: "PostHog",
    category: "monitoring",
    websiteUrl: "https://posthog.com",
    pricingUrl: "https://posthog.com/pricing",
    repo: "PostHog/posthog",
    pricingModel: "freemium",
    tagline: "Analytics produit, replays et feature flags.",
  },
  {
    slug: "prometheus",
    name: "Prometheus",
    category: "monitoring",
    websiteUrl: "https://prometheus.io",
    repo: "prometheus/prometheus",
    pricingModel: "open_source",
    audience: "pro",
  },
  {
    slug: "openobserve",
    name: "OpenObserve",
    category: "monitoring",
    websiteUrl: "https://openobserve.ai",
    repo: "openobserve/openobserve",
    pricingModel: "open_source",
  },

  // ----------------------------------------------------------------- email
  {
    slug: "resend",
    name: "Resend",
    category: "email",
    websiteUrl: "https://resend.com",
    pricingUrl: "https://resend.com/pricing",
    pricingModel: "freemium",
    tagline: "Emails transactionnels avec templates React.",
    baselinePopularity: 74,
    baselineStability: 70,
  },
  {
    slug: "postmark",
    name: "Postmark",
    category: "email",
    websiteUrl: "https://postmarkapp.com",
    pricingUrl: "https://postmarkapp.com/pricing",
    pricingModel: "paid",
    tagline: "Délivrabilité transactionnelle réputée.",
    baselinePopularity: 66,
    baselineStability: 84,
  },
  {
    slug: "sendgrid",
    name: "SendGrid",
    category: "email",
    websiteUrl: "https://sendgrid.com",
    pricingUrl: "https://sendgrid.com/en-us/pricing",
    pricingModel: "freemium",
    baselinePopularity: 80,
    baselineStability: 82,
  },
  {
    slug: "brevo",
    name: "Brevo",
    category: "email",
    websiteUrl: "https://brevo.com",
    pricingUrl: "https://www.brevo.com/pricing",
    pricingModel: "freemium",
    tagline: "Transactionnel et marketing réunis, hébergement UE.",
    baselinePopularity: 68,
    baselineStability: 76,
  },
  {
    slug: "amazon-ses",
    name: "Amazon SES",
    category: "email",
    websiteUrl: "https://aws.amazon.com/ses",
    pricingUrl: "https://aws.amazon.com/ses/pricing",
    pricingModel: "usage",
    tagline: "Le moins cher à l’échelle, au prix d’une configuration AWS.",
    baselinePopularity: 82,
    baselineStability: 90,
  },
  {
    slug: "listmonk",
    name: "Listmonk",
    category: "email",
    websiteUrl: "https://listmonk.app",
    repo: "knadh/listmonk",
    pricingModel: "open_source",
    tagline: "Newsletters auto-hébergées, un seul binaire.",
  },

  // --------------------------------------------------------------- storage
  {
    slug: "cloudflare-r2",
    name: "Cloudflare R2",
    category: "storage",
    websiteUrl: "https://developers.cloudflare.com/r2",
    pricingUrl: "https://developers.cloudflare.com/r2/pricing",
    pricingModel: "freemium",
    tagline: "Stockage objet compatible S3, sans frais de sortie.",
    baselinePopularity: 78,
    baselineStability: 82,
  },
  {
    slug: "backblaze-b2",
    name: "Backblaze B2",
    category: "storage",
    websiteUrl: "https://backblaze.com/cloud-storage",
    pricingUrl: "https://www.backblaze.com/cloud-storage/pricing",
    pricingModel: "usage",
    baselinePopularity: 68,
    baselineStability: 84,
  },
  {
    slug: "aws-s3",
    name: "Amazon S3",
    category: "storage",
    websiteUrl: "https://aws.amazon.com/s3",
    pricingUrl: "https://aws.amazon.com/s3/pricing",
    pricingModel: "usage",
    baselinePopularity: 96,
    baselineStability: 96,
  },
  {
    slug: "minio",
    name: "MinIO",
    category: "storage",
    websiteUrl: "https://min.io",
    repo: "minio/minio",
    pricingModel: "open_source",
    audience: "pro",
  },
  {
    slug: "uploadthing",
    name: "UploadThing",
    category: "storage",
    websiteUrl: "https://uploadthing.com",
    pricingUrl: "https://uploadthing.com/pricing",
    pricingModel: "freemium",
    audience: "solo",
    baselinePopularity: 58,
    baselineStability: 58,
  },

  // ------------------------------------------------------------------ saas
  {
    slug: "cursor",
    name: "Cursor",
    category: "saas",
    websiteUrl: "https://cursor.com",
    pricingUrl: "https://cursor.com/pricing",
    pricingModel: "freemium",
    tagline: "Éditeur de code assisté par IA.",
    baselinePopularity: 88,
    baselineStability: 68,
  },
  {
    slug: "github-copilot",
    name: "GitHub Copilot",
    category: "saas",
    websiteUrl: "https://github.com/features/copilot",
    pricingUrl: "https://github.com/features/copilot/plans",
    pricingModel: "freemium",
    baselinePopularity: 92,
    baselineStability: 82,
  },
  {
    slug: "figma",
    name: "Figma",
    category: "saas",
    websiteUrl: "https://figma.com",
    pricingUrl: "https://www.figma.com/pricing",
    pricingModel: "freemium",
    baselinePopularity: 94,
    baselineStability: 90,
  },
  {
    slug: "linear",
    name: "Linear",
    category: "saas",
    websiteUrl: "https://linear.app",
    pricingUrl: "https://linear.app/pricing",
    pricingModel: "freemium",
    baselinePopularity: 78,
    baselineStability: 80,
  },
  {
    slug: "notion",
    name: "Notion",
    category: "saas",
    websiteUrl: "https://notion.so",
    pricingUrl: "https://www.notion.com/pricing",
    pricingModel: "freemium",
    baselinePopularity: 92,
    baselineStability: 86,
  },
  {
    slug: "plausible",
    name: "Plausible Analytics",
    category: "saas",
    websiteUrl: "https://plausible.io",
    pricingUrl: "https://plausible.io/#pricing",
    repo: "plausible/analytics",
    pricingModel: "open_source",
    tagline: "Analytics sans cookies, auto-hébergeable.",
  },
  {
    slug: "umami",
    name: "Umami",
    category: "saas",
    websiteUrl: "https://umami.is",
    repo: "umami-software/umami",
    pricingModel: "open_source",
    audience: "solo",
  },
  {
    slug: "n8n",
    name: "n8n",
    category: "saas",
    websiteUrl: "https://n8n.io",
    pricingUrl: "https://n8n.io/pricing",
    repo: "n8n-io/n8n",
    pricingModel: "freemium",
    tagline: "Automatisation de workflows, auto-hébergeable.",
  },
  {
    slug: "directus",
    name: "Directus",
    category: "saas",
    websiteUrl: "https://directus.io",
    repo: "directus/directus",
    pricingModel: "open_source",
  },
  {
    slug: "strapi",
    name: "Strapi",
    category: "saas",
    websiteUrl: "https://strapi.io",
    pricingUrl: "https://strapi.io/pricing-cloud",
    repo: "strapi/strapi",
    pricingModel: "freemium",
  },
  {
    slug: "appwrite",
    name: "Appwrite",
    category: "saas",
    websiteUrl: "https://appwrite.io",
    pricingUrl: "https://appwrite.io/pricing",
    repo: "appwrite/appwrite",
    pricingModel: "freemium",
  },
  {
    slug: "storybook",
    name: "Storybook",
    category: "saas",
    websiteUrl: "https://storybook.js.org",
    repo: "storybookjs/storybook",
    pricingModel: "open_source",
  },
];

export const SEED_BY_SLUG = new Map(TOOL_SEEDS.map((seed) => [seed.slug, seed]));
